### ISSUE TITLE
Compilation fails due to unresolved dependencies

### ISSUE THREAD

**Issue by tampler** [LBL-CoDEx/OpenSoCFabric#6]
Hello 

I'm trying to compile this project, but sbt fails with the following msg:

[warn] 	Note: Unresolved dependencies path:
[warn] 		com.github.scct:sbt-scct:0.2 (scalaVersion=2.10, sbtVersion=1.0) (/home/bku/work/cores/chisel/OpenSoCFabric/build.sbt#L14-15)
[warn] 		  +- gov.lbl.crd.csd.cag:opensoc_2.10:1.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.scct#sbt-scct;0.2: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)

Pls update the build script appropriately

**Comment by tampler** [comment]
Not actual
